/**
 * ID Generation Utilities - DEPRECATED FOR TRADE IDS
 * 
 * ═══════════════════════════════════════════════════════════════════════════════
 * ⚠️  DEPRECATED FOR TRADE IDS: UUIDs are now generated by the DATABASE
 * ═══════════════════════════════════════════════════════════════════════════════
 * 
 * As of the DB-first UUID migration, trade and position IDs are generated by
 * Supabase using gen_random_uuid() as the default primary key.
 * 
 * DO NOT use generateTradeId() or generatePositionId() for trades.
 * 
 * FOR TRADE IDS:
 * 1. Insert trade WITHOUT id field
 * 2. Supabase uses gen_random_uuid() as default  
 * 3. Capture returned ID via .select('id').single()
 * 4. Attach ID to in-memory objects
 * 
 * generateUUID() is still valid for non-trade use cases like:
 * - Correlation IDs
 * - Request IDs
 * - Session IDs
 * ═══════════════════════════════════════════════════════════════════════════════
 */

import { 
    generateTradeId as generateHardenedTradeId,
    generatePositionId as generateHardenedPositionId,
    generateUUID as generateHardenedUUID 
} from './tradeId';

/**
 * @deprecated Trade IDs are now generated by the database.
 * Do not use this for trade IDs. The database generates them via gen_random_uuid().
 * 
 * @param attempt - Optional retry attempt number for collision recovery
 * @returns A collision-resistant unique ID string
 */
export function generateTradeId(attempt: number = 0): string {
    console.warn('[DEPRECATED] generateTradeId() - trade IDs come from database now');
    return generateHardenedTradeId(attempt);
}

/**
 * @deprecated Position IDs should use the trade ID from the database.
 * Do not use this for position IDs.
 * 
 * @param attempt - Optional retry attempt number for collision recovery
 * @returns A collision-resistant unique ID string
 */
export function generatePositionId(attempt: number = 0): string {
    console.warn('[DEPRECATED] generatePositionId() - use trade ID from database');
    return generateHardenedPositionId(attempt);
}

/**
 * Generate a collision-resistant UUID for any purpose.
 * 
 * This is still valid for non-trade use cases like:
 * - Correlation IDs
 * - Request IDs  
 * - Session IDs
 * 
 * @param attempt - Optional retry attempt number for collision recovery
 * @returns A collision-resistant unique ID string
 */
export function generateUUID(attempt: number = 0): string {
    return generateHardenedUUID(attempt);
}

