/**
 * Trade ID Generation - DEPRECATED
 * 
 * ═══════════════════════════════════════════════════════════════════════════════
 * ⚠️  DEPRECATED: Trade IDs are now generated by the DATABASE
 * ═══════════════════════════════════════════════════════════════════════════════
 * 
 * As of the DB-first UUID migration, trade IDs are generated by Supabase
 * using gen_random_uuid() as the default primary key.
 * 
 * DO NOT use these functions for trade IDs.
 * 
 * The functions below are kept only for backward compatibility with non-trade
 * use cases (e.g., correlation IDs, request IDs, etc.).
 * 
 * FOR TRADE IDS:
 * 1. Insert trade WITHOUT id field
 * 2. Supabase uses gen_random_uuid() as default
 * 3. Capture returned ID via .select('id').single()
 * 4. Attach ID to in-memory objects
 * 
 * ═══════════════════════════════════════════════════════════════════════════════
 */

import { randomUUID } from "crypto";

/**
 * @deprecated Trade IDs are now generated by the database using gen_random_uuid().
 * Do not use this for trade IDs. Only use for non-trade purposes like correlation IDs.
 * 
 * Generates a collision-resistant ID using:
 * - crypto.randomUUID() for cryptographic randomness
 * - nanosecond timestamp entropy for uniqueness
 * 
 * @param attempt - Retry attempt number (0 for first attempt)
 * @returns Globally unique ID
 */
export function generateTradeId(attempt: number = 0): string {
    console.warn('[DEPRECATED] generateTradeId() called - trade IDs should come from database');
    const base = randomUUID();
    const nano = process.hrtime.bigint().toString();

    // Include attempt number only if > 0 (collision retry)
    return attempt > 0 ? `${base}-${nano}-r${attempt}` : `${base}-${nano}`;
}

/**
 * @deprecated Position IDs should use the trade ID from the database.
 * 
 * @param attempt - Retry attempt number (0 for first attempt)
 * @returns Globally unique position ID
 */
export function generatePositionId(attempt: number = 0): string {
    console.warn('[DEPRECATED] generatePositionId() called - use trade ID from database');
    return generateTradeId(attempt);
}

/**
 * Generates a collision-resistant generic UUID.
 * This is still valid for non-trade use cases like correlation IDs, request IDs, etc.
 * 
 * @param attempt - Retry attempt number (0 for first attempt)
 * @returns Globally unique ID
 */
export function generateUUID(attempt: number = 0): string {
    const base = randomUUID();
    const nano = process.hrtime.bigint().toString();

    return attempt > 0 ? `${base}-${nano}-r${attempt}` : `${base}-${nano}`;
}

